//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUPON_RUBRO
    {
        public decimal CUPON_RUBRO_ID { get; set; }
        public decimal CUPON_FK { get; set; }
        public decimal RUBRO_FK { get; set; }
    
        public virtual CUPON CUPON { get; set; }
        public virtual RUBRO RUBRO { get; set; }
    }
}
