//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUPON
    {
        public CUPON()
        {
            this.CUPON_RUBRO = new HashSet<CUPON_RUBRO>();
            this.CUPON_CONSUMIDOR = new HashSet<CUPON_CONSUMIDOR>();
        }
    
        public decimal ID_CUPON { get; set; }
        public string PDF { get; set; }
        public decimal TOPE_MAXIMO { get; set; }
        public System.DateTime FECHA { get; set; }
    
        public virtual ICollection<CUPON_RUBRO> CUPON_RUBRO { get; set; }
        public virtual ICollection<CUPON_CONSUMIDOR> CUPON_CONSUMIDOR { get; set; }
    }
}
