//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entidades : DbContext
    {
        public Entidades()
            : base("name=Entidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CAMPANA> CAMPANA { get; set; }
        public DbSet<CONSUMIDOR> CONSUMIDOR { get; set; }
        public DbSet<CUPON> CUPON { get; set; }
        public DbSet<CUPON_CONSUMIDOR> CUPON_CONSUMIDOR { get; set; }
        public DbSet<CUPON_RUBRO> CUPON_RUBRO { get; set; }
        public DbSet<EMPRESA> EMPRESA { get; set; }
        public DbSet<ESCALA> ESCALA { get; set; }
        public DbSet<OFERTA> OFERTA { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
        public DbSet<ROL_USUARIO> ROL_USUARIO { get; set; }
        public DbSet<RUBRO> RUBRO { get; set; }
        public DbSet<TIENDA> TIENDA { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<VALORACION> VALORACION { get; set; }
    }
}
