//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESCALA
    {
        public ESCALA()
        {
            this.VALORACION = new HashSet<VALORACION>();
        }
    
        public decimal ID_ESCALA { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<VALORACION> VALORACION { get; set; }
    }
}
